import {randomUUID,randomBytes,createHash,createHmac,createCipheriv,createDecipheriv} from 'node:crypto';

export const TERMS_VERSION='wasil-captain-2026-10-03';
export const TERMS=[
 'أقر بصحة الاسم وبيانات الهوية والمركبة والمستندات المرفقة، وبأنها تخصني أو أن لدي صلاحية استخدامها.',
 'ألتزم بسريان الرخصة والاستمارة والتأمين، وتحديثها قبل انتهاء صلاحيتها، ولا أستقبل طلبات خارج الخدمات المعتمدة لحسابي.',
 'ألتزم بالمحافظة على الحمولة وخصوصية العميل وعدم مشاركة الحساب، وبالتواصل مع الدعم عند تعذر تنفيذ الطلب.',
 'أوافق على معالجة بيانات طلبي ومستنداتي من إدارة واصل لغرض مراجعة التسجيل وتشغيل الحساب، وعلى إرسال نتيجة الطلب إلى جوالي وبريدي.',
 'أفهم أن إرسال الطلب لا يعني القبول، وأن الإدارة قد تطلب تحديث البيانات أو ترفض الطلب مع توضيح السبب.'
];
export const CATEGORIES={light:'خفيف',heavy:'ثقيل',home:'منزلي'};
export const FILE_KINDS={license:'رخصة القيادة',registration:'استمارة المركبة',insurance:'التأمين',exterior:'صور المركبة من الخارج',interior:'صور المركبة من الداخل'};
const MAX_FILE=4*1024*1024,MAX_TOTAL=40*1024*1024;
export const dateToday=()=>new Date(Date.now()+3*3600000).toISOString().slice(0,10);
const error=(status,message)=>{throw Object.assign(new Error(message),{status});};
const txt=(v,label,max=200)=>{if(typeof v!=='string'||!v.trim()||v.length>max)error(400,`تحقق من ${label}`);return v.trim();};
export function normalizePhone(v){let s=String(v??'').replace(/[٠-٩]/g,x=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(x))).replace(/[\s()-]/g,'');if(s.startsWith('00'))s='+'+s.slice(2);if(/^05\d{8}$/.test(s))s='+966'+s.slice(1);if(/^9665\d{8}$/.test(s))s='+'+s;if(!/^\+9665\d{8}$/.test(s))error(400,'أدخل رقم جوال سعودي صحيحًا مثل 05xxxxxxxx');return s;}
function future(v,label){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v||v<dateToday())error(400,`${label} يجب أن تكون سارية`);return v;}
function categories(v){if(!Array.isArray(v)||!v.length||v.length>3||v.some(x=>!Object.hasOwn(CATEGORIES,x)))error(400,'اختر نوع مشاوير صحيحًا واحدًا على الأقل');return [...new Set(v)].sort();}
function details(b){const fullName=txt(b.fullName,'الاسم الرباعي',120);if(fullName.split(/\s+/u).length<4)error(400,'أدخل الاسم الرباعي كما في الهوية');const identity=txt(b.identityNumber,'رقم الهوية أو الإقامة');if(!/^[12][0-9]{9}$/.test(identity))error(400,'رقم الهوية أو الإقامة 10 أرقام ويبدأ بـ 1 أو 2');const v=b.vehicle;if(!v||typeof v!=='object')error(400,'أكمل بيانات المركبة');const year=Number(v.year);if(!Number.isInteger(year)||year<1950||year>new Date().getUTCFullYear()+1)error(400,'سنة الصنع غير صحيحة');const vin=txt(v.vin,'رقم الهيكل',17).toUpperCase();if(!/^[A-HJ-NPR-Z0-9]{17}$/.test(vin))error(400,'رقم الهيكل 17 حرفًا إنجليزيًا ورقمًا دون I أو O أو Q');return {fullName,phone:normalizePhone(b.phone),email:txt(b.email,'البريد الإلكتروني',160).toLowerCase(),identityNumber:identity,vehicle:{type:txt(v.type,'نوع المركبة',80),model:txt(v.model,'موديل المركبة',80),year,vin},categories:categories(b.categories),licenseExpiry:future(b.licenseExpiry,'رخصة القيادة'),registrationExpiry:future(b.registrationExpiry,'الاستمارة'),insuranceExpiry:future(b.insuranceExpiry,'وثيقة التأمين')};}
function fileType(buffer){if(buffer.length<12)return null;if(buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return 'image/png';if(buffer[0]===255&&buffer[1]===216&&buffer[2]===255)return 'image/jpeg';if(buffer.subarray(0,4).toString()==='RIFF'&&buffer.subarray(8,12).toString()==='WEBP')return 'image/webp';if(buffer.subarray(0,5).toString()==='%PDF-'&&buffer.subarray(-1024).includes(Buffer.from('%%EOF')))return 'application/pdf';return null;}

export function createOnboarding(db,{send,passwordHash,validPassword,env=process.env}){
 const secret=env.CAPTAIN_DATA_KEY||(env.NODE_ENV==='production'?'':'local-onboarding-test-key-not-for-production');
 if(secret.length<32)throw new Error('CAPTAIN_DATA_KEY (32+ characters) is required for protected onboarding data');
 const key=createHash('sha256').update(secret).digest();
 const seal=b=>{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,cipher.update(Buffer.isBuffer(b)?b:Buffer.from(JSON.stringify(b))),cipher.final(),cipher.getAuthTag()]);};
 const open=b=>{b=Buffer.from(b);const cipher=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));cipher.setAuthTag(b.subarray(-16));return Buffer.concat([cipher.update(b.subarray(12,-16)),cipher.final()]);};
 const decode=b=>JSON.parse(open(b).toString());
 const fingerprint=(kind,s)=>createHmac('sha256',key).update(kind+':'+s).digest('hex');
 db.exec(`CREATE TABLE IF NOT EXISTS captain_applications (
 user_id TEXT PRIMARY KEY REFERENCES users(id), status TEXT NOT NULL DEFAULT 'draft', revision INTEGER NOT NULL DEFAULT 1,
 phone_hash TEXT UNIQUE NOT NULL,identity_hash TEXT UNIQUE NOT NULL,payload BLOB NOT NULL,files TEXT NOT NULL DEFAULT '[]',
 username TEXT UNIQUE,approved_categories TEXT NOT NULL DEFAULT '[]',online INTEGER NOT NULL DEFAULT 0,heartbeat INTEGER NOT NULL DEFAULT 0,
 submitted_at TEXT,reviewed_at TEXT,reviewed_by TEXT REFERENCES users(id),reason TEXT NOT NULL DEFAULT '',terms_version TEXT,terms_at TEXT);
 CREATE TABLE IF NOT EXISTS captain_files (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,body BLOB NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS captain_reviews (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),revision INTEGER NOT NULL,decision TEXT NOT NULL,reason TEXT NOT NULL,reviewer TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,snapshot BLOB NOT NULL,UNIQUE(user_id,revision));
 CREATE TABLE IF NOT EXISTS notification_outbox (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),revision INTEGER NOT NULL,channel TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'queued',payload BLOB NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_attempt INTEGER NOT NULL DEFAULT 0,provider_id TEXT,last_error TEXT,created_at TEXT NOT NULL,UNIQUE(user_id,revision,channel));
 CREATE INDEX IF NOT EXISTS captain_application_status ON captain_applications(status,submitted_at);
 `);
 // Detect a lost/replaced encryption key before accepting any new request.
 const first=db.prepare('SELECT payload FROM captain_applications LIMIT 1').get();if(first)decode(first.payload);
 const get=id=>db.prepare('SELECT * FROM captain_applications WHERE user_id=?').get(id);
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const value=fn();db.exec('COMMIT');return value;}catch(e){db.exec('ROLLBACK');throw e;}};
 const current=r=>{if(!r)return false;const d=decode(r.payload),today=dateToday();return [d.licenseExpiry,d.registrationExpiry,d.insuranceExpiry].every(x=>x>=today);};
 const eligible=(user,r=get(user.id))=>!!user.approved&&r?.status==='approved'&&current(r);
 const effective=(user,r=get(user.id))=>eligible(user,r)&&!!r.online&&r.heartbeat>Date.now()-120000;
 const fileMetadata=r=>JSON.parse(r.files).map(id=>db.prepare('SELECT id,kind,mime,size,created_at AS createdAt FROM captain_files WHERE id=? AND user_id=?').get(id,r.user_id)).filter(Boolean);
 const summary=(user,r=get(user.id))=>({applicationStatus:r?.status||'incomplete',applicationRevision:r?.revision||0,username:r?.username||null,categories:r?JSON.parse(r.approved_categories):[],requestedCategories:r?decode(r.payload).categories:[],online:effective(user,r),documentsCurrent:r?current(r):false,rejectionReason:r?.status==='rejected'?r.reason:'',submittedAt:r?.submitted_at||null,reviewedAt:r?.reviewed_at||null});
 function application(user,r=get(user.id)){if(!r)return {status:'incomplete',revision:0,data:{fullName:user.name,email:user.email},files:[],termsVersion:TERMS_VERSION,terms:TERMS};return {status:r.status,revision:r.revision,data:decode(r.payload),files:fileMetadata(r),username:r.username,approvedCategories:JSON.parse(r.approved_categories),reason:r.reason,submittedAt:r.submitted_at,reviewedAt:r.reviewed_at,termsAcceptedAt:r.terms_at,termsVersion:TERMS_VERSION,terms:TERMS,documentsCurrent:current(r)};}
 function save(user,b){const d=details({...b,email:user.email});const r=get(user.id);if(r&&['pending','approved'].includes(r.status))error(409,'لا يمكن تعديل طلب قيد المراجعة أو معتمد');const phoneHash=fingerprint('phone',d.phone),identityHash=fingerprint('identity',d.identityNumber);const other=db.prepare('SELECT user_id FROM captain_applications WHERE (phone_hash=? OR identity_hash=?) AND user_id<>?').get(phoneHash,identityHash,user.id);if(other)error(409,'رقم الجوال أو الهوية مرتبط بطلب كابتن آخر');if(r){db.prepare("UPDATE captain_applications SET payload=?,phone_hash=?,identity_hash=?,status='draft',revision=revision+CASE WHEN status='rejected' THEN 1 ELSE 0 END,online=0,reason='',submitted_at=NULL,terms_at=NULL,terms_version=NULL WHERE user_id=?").run(seal(d),phoneHash,identityHash,user.id);}else db.prepare('INSERT INTO captain_applications(user_id,phone_hash,identity_hash,payload) VALUES(?,?,?,?)').run(user.id,phoneHash,identityHash,seal(d));db.prepare('UPDATE users SET name=? WHERE id=?').run(d.fullName,user.id);return application({...user,name:d.fullName});}
 function register(b){const d=details(b);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))error(400,'البريد الإلكتروني غير صحيح');if(typeof b.password!=='string'||b.password.length>128||!validPassword(b.password))error(400,'كلمة المرور 8 أحرف على الأقل مع حرف كبير وحرف صغير ورقم');if(b.confirmPassword!==b.password)error(400,'تأكيد كلمة المرور غير مطابق');if(db.prepare("SELECT id FROM users WHERE role='captain' AND email=?").get(d.email))error(409,'الحساب موجود؛ سجّل الدخول لإكمال طلبك');const user={id:randomUUID(),name:d.fullName,email:d.email,role:'captain',approved:0};return transaction(()=>{db.prepare('INSERT INTO users(id,role,email,name,hash,approved) VALUES(?,?,?,?,?,0)').run(user.id,'captain',d.email,d.fullName,passwordHash(b.password));save(user,d);return {ok:true,pendingApproval:true,applicationStatus:'draft'};});}
 function upload(user,b){const r=get(user.id);if(!r||r.status!=='draft')error(409,'احفظ بيانات طلب التسجيل قبل رفع الملفات');if(!Object.hasOwn(FILE_KINDS,b.kind))error(400,'نوع المرفق غير صحيح');if(typeof b.base64!=='string'||!b.base64.length||b.base64.length>Math.ceil(MAX_FILE/3)*4||b.base64.length%4!==0||/[^A-Za-z0-9+/=]/.test(b.base64)||!/^[^=]*={0,2}$/.test(b.base64))error(400,'ملف غير صالح أو أكبر من 4 ميجابايت');const buf=Buffer.from(b.base64,'base64'),mime=fileType(buf);if(!mime||!buf.length||buf.length>MAX_FILE)error(400,'يسمح فقط بصور JPG وPNG وWebP أو مستند PDF صالح');if(['exterior','interior'].includes(b.kind)&&mime==='application/pdf')error(400,'صور المركبة يجب أن تكون صورًا وليست PDF');const total=db.prepare('SELECT COALESCE(SUM(size),0) AS n FROM captain_files WHERE user_id=?').get(user.id).n;if(total+buf.length>MAX_TOTAL)error(413,'تجاوزت مساحة مرفقات الحساب المسموحة');const meta=fileMetadata(r);if(['exterior','interior'].includes(b.kind)&&meta.filter(x=>x.kind===b.kind).length>=5)error(400,'الحد الأقصى 5 صور لكل جهة');const id=randomUUID();transaction(()=>{db.prepare('INSERT INTO captain_files VALUES(?,?,?,?,?,?,?)').run(id,user.id,b.kind,mime,buf.length,seal(buf),new Date().toISOString());const ids=meta.filter(x=>['exterior','interior'].includes(b.kind)||x.kind!==b.kind).map(x=>x.id);ids.push(id);db.prepare('UPDATE captain_applications SET files=? WHERE user_id=?').run(JSON.stringify(ids),user.id);});return {id,kind:b.kind,mime,size:buf.length};}
 function submit(user,b){const r=get(user.id);if(!r)error(409,'أكمل بيانات الطلب');if(r.status==='pending')return application(user,r);if(r.status!=='draft')error(409,'الطلب ليس مسودة');details(decode(r.payload));if(b.termsAccepted!==true||b.termsVersion!==TERMS_VERSION)error(400,'يجب قراءة الشروط والموافقة على الإقرار');const meta=fileMetadata(r);for(const kind of Object.keys(FILE_KINDS))if(!meta.some(x=>x.kind===kind))error(400,`أرفق ${FILE_KINDS[kind]}`);const now=new Date().toISOString();db.prepare("UPDATE captain_applications SET status='pending',submitted_at=?,terms_at=?,terms_version=?,online=0 WHERE user_id=?").run(now,now,TERMS_VERSION,user.id);return application(user);}
 function notifications(id){return db.prepare('SELECT id,revision,channel,state,attempts,provider_id AS providerId,last_error AS error,created_at AS createdAt FROM notification_outbox WHERE user_id=? ORDER BY created_at DESC').all(id);}
 function review(admin,id,b){return transaction(()=>{const user=db.prepare("SELECT * FROM users WHERE id=? AND role='captain'").get(id),r=get(id);if(!user||!r)error(404,'طلب التسجيل غير موجود');if(r.status!=='pending'||b.revision!==r.revision)error(409,'تغيّرت حالة الطلب؛ حدّث الصفحة قبل اتخاذ القرار');if(!['approved','rejected'].includes(b.decision))error(400,'اختر قبولًا أو رفضًا');const reason=b.decision==='rejected'?txt(b.reason,'سبب الرفض',500):'';let allowed=[];if(b.decision==='approved'){if(!current(r))error(409,'توجد وثيقة منتهية؛ لا يمكن اعتماد الطلب');allowed=categories(b.categories??decode(r.payload).categories);if(allowed.some(x=>!decode(r.payload).categories.includes(x)))error(400,'لا يمكن اعتماد نوع مشاوير لم يختره الكابتن');}db.prepare("UPDATE notification_outbox SET state='superseded',last_error=NULL WHERE user_id=? AND state IN ('queued','blocked')").run(id);const now=new Date().toISOString(),username=r.username||(b.decision==='approved'?'WS'+randomBytes(5).toString('hex').toUpperCase():null),d=decode(r.payload);db.prepare('INSERT INTO captain_reviews VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),id,r.revision,b.decision,reason,admin.id,now,seal({data:d,files:JSON.parse(r.files),termsVersion:r.terms_version,termsAt:r.terms_at}));db.prepare('UPDATE captain_applications SET status=?,reason=?,username=?,approved_categories=?,reviewed_at=?,reviewed_by=?,online=0,heartbeat=0 WHERE user_id=?').run(b.decision,reason,username,JSON.stringify(allowed),now,admin.id,id);db.prepare('UPDATE users SET approved=? WHERE id=?').run(b.decision==='approved'?1:0,id);const body=b.decision==='approved'?`واصل: تم قبول طلب تسجيلك ككابتن. اسم المستخدم: ${username}. يمكنك الدخول برقم جوالك أو بريدك أو اسم المستخدم وبكلمة مرورك. الخدمات المعتمدة: ${allowed.map(x=>CATEGORIES[x]).join('، ')}.`:`واصل: تم رفض طلب تسجيلك ككابتن. السبب: ${reason}. يمكنك مراجعة بياناتك وإعادة تقديم الطلب من تطبيق الكابتن.`;for(const channel of ['sms','email'])db.prepare('INSERT INTO notification_outbox(id,user_id,revision,channel,payload,created_at) VALUES(?,?,?,?,?,?)').run(randomUUID(),id,r.revision,channel,seal({to:channel==='sms'?d.phone:d.email,subject:'واصل — نتيجة طلب تسجيل كابتن',body}),now);return {application:application({...user,approved:b.decision==='approved'}),notifications:notifications(id)};});}
 function resolve(identifier){identifier=String(identifier||'').trim();let phoneHash='';try{phoneHash=fingerprint('phone',normalizePhone(identifier));}catch{}return db.prepare("SELECT u.* FROM users u LEFT JOIN captain_applications a ON a.user_id=u.id WHERE u.role='captain' AND (u.email=? OR a.username=? OR a.phone_hash=?)").get(identifier.toLowerCase(),identifier.toUpperCase(),phoneHash);}
 function listOrders(user){const r=get(user.id),allowed=effective(user,r)?JSON.parse(r.approved_categories):[];const own=db.prepare("SELECT * FROM orders WHERE captain_id=? ORDER BY CASE WHEN status IN ('delivered','cancelled') THEN 1 ELSE 0 END,created_at DESC LIMIT 100").all(user.id);const busy=own.some(o=>!['delivered','cancelled'].includes(o.status));if(busy||!allowed.length)return own;const available=db.prepare("SELECT * FROM orders WHERE status='searching' AND captain_id IS NULL AND json_extract(data,'$.category') IN (SELECT value FROM json_each(?)) ORDER BY created_at DESC LIMIT 100").all(JSON.stringify(allowed));return [...available,...own];}
 function assertAccept(user,row){if(!effective(user))error(403,'فعّل متصل الآن بعد اعتماد الحساب وسريان المستندات');const r=get(user.id);if(!JSON.parse(r.approved_categories).includes(JSON.parse(row.data).category))error(403,'نوع المشوار غير معتمد لحسابك');if(db.prepare("SELECT id FROM orders WHERE captain_id=? AND status NOT IN ('delivered','cancelled')").get(user.id))error(409,'أكمل رحلتك الحالية قبل قبول طلب آخر');}
 async function handle(req,res,role,action,user,b){
  const method=req.method;
  if(role==='captain'&&action==='application'&&method==='GET'){send(res,200,application(user));return true;}
  if(role==='captain'&&action==='application'&&method==='PATCH'){send(res,200,save(user,b));return true;}
  if(role==='captain'&&action==='application/files'&&method==='POST'){send(res,201,upload(user,b));return true;}
  if(role==='captain'&&/^application\/files\/[\w-]+$/.test(action)&&method==='DELETE'){const r=get(user.id);if(!r||r.status!=='draft')error(409,'المرفقات مقفلة أثناء المراجعة');const id=action.split('/').at(-1);db.prepare('UPDATE captain_applications SET files=? WHERE user_id=?').run(JSON.stringify(JSON.parse(r.files).filter(x=>x!==id)),user.id);send(res,200,{ok:true});return true;}
  if(role==='captain'&&action==='application/submit'&&method==='POST'){send(res,200,submit(user,b));return true;}
  if(role==='captain'&&action==='availability'&&method==='POST'){if(typeof b.online!=='boolean')error(400,'حالة الاتصال غير صحيحة');if(b.online&&!eligible(user))error(403,'يلزم قبول طلب التسجيل وسريان جميع الوثائق');db.prepare('UPDATE captain_applications SET online=?,heartbeat=? WHERE user_id=?').run(b.online?1:0,b.online?Date.now():0,user.id);send(res,200,{online:effective(user),expiresInSeconds:b.online?120:0});return true;}
  if(role==='captain'&&action==='heartbeat'&&method==='POST'){if(eligible(user))db.prepare('UPDATE captain_applications SET heartbeat=? WHERE user_id=? AND online=1').run(Date.now(),user.id);send(res,200,{online:effective(user)});return true;}
  if(role==='admin'&&action==='captain-applications'&&method==='GET'){const rows=db.prepare("SELECT u.* FROM users u JOIN captain_applications a ON a.user_id=u.id WHERE a.status<>'draft' ORDER BY a.submitted_at DESC LIMIT 200").all();send(res,200,rows.map(u=>({id:u.id,name:u.name,...summary(u)})));return true;}
  const request=action.match(/^captain-applications\/([\w-]+)(\/decision)?$/);
  if(role==='admin'&&request){const u=db.prepare("SELECT * FROM users WHERE role='captain' AND id=?").get(request[1]);if(!u)error(404,'الطلب غير موجود');if(method==='GET'&&!request[2]){send(res,200,{...application(u),id:u.id,notifications:notifications(u.id),history:db.prepare('SELECT revision,decision,reason,created_at AS createdAt FROM captain_reviews WHERE user_id=? ORDER BY revision DESC').all(u.id)});return true;}if(method==='POST'&&request[2]){send(res,200,review(user,u.id,b));return true;}}
  const download=action.match(/^files\/([\w-]+)$/);
  if(['captain','admin'].includes(role)&&download&&method==='GET'){const f=db.prepare('SELECT * FROM captain_files WHERE id=?').get(download[1]);if(!f||(role==='captain'&&f.user_id!==user.id))error(404,'المرفق غير موجود');const bytes=open(f.body),ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','application/pdf':'pdf'}[f.mime];res.writeHead(200,{'Content-Type':f.mime,'Content-Length':bytes.length,'Content-Disposition':`attachment; filename="${f.kind}.${ext}"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"});res.end(bytes);return true;}
  return false;
 }
 return {register,resolve,summary,application,handle,listOrders,assertAccept,eligible,seal,decode,get,notifications,offline:id=>db.prepare('UPDATE captain_applications SET online=0,heartbeat=0 WHERE user_id=?').run(id)};
}
